### ISSUE TITLE
I'm desperate)) Issue with esp32_compisite_video -    error: implicit declaration of function

### ISSUE THREAD

**Issue by Igor-kopanitsa** [danjulio/tCamMiniAnalog#2]
HI all,

I've tried different versions of IDF  4.4.4.,   4.4.6   But always get same issue with simple code -  video_test_pal(VIDEO_TEST_PM5544) of the "esp32_composite_video"   component.

error: implicit declaration of function 'video_test_pal'; did you mean 'video_stop'? [-Werror=implicit-function-declaration]
     video_test_pal(VIDEO_TEST_PM5544);
     ^~~~~~~~~~~~~~

I would be appreciated for any hint. My vision blurry right now))

...the last error part of building info:

FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj
C:\epressif\tools\tools\xtensa-esp32-elf\esp-2021r2-patch5-8.4.0\xtensa-esp32-elf\bin\xtensa-esp32-elf-gcc.exe -DHAVE_CONFIG_H -DLV_CONF_INCLUDE_SIMPLE -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DUNITY_INCLUDE_CONFIG_H -DWITH_POSIX -IC:/Video_comp_esp32/build/config -IC:/Video_comp_esp32/main -IC:/epressif/v4.4.4/esp-idf/components/newlib/platform_include -IC:/epressif/v4.4.4/esp-idf/components/freertos/include -IC:/epressif/v4.4.4/esp-idf/components/freertos/include/esp_additions/freertos -IC:/epressif/v4.4.4/esp-idf/components/freertos/port/xtensa/include -IC:/epressif/v4.4.4/esp-idf/components/freertos/include/esp_additions -IC:/epressif/v4.4.4/esp-idf/components/esp_hw_support/include -IC:/epressif/v4.4.4/esp-idf/components/esp_hw_support/include/soc -IC:/epressif/v4.4.4/esp-idf/components/esp_hw_support/include/soc/esp32 -IC:/epressif/v4.4.4/esp-idf/components/esp_hw_support/port/esp32/. -IC:/epressif/v4.4.4/esp-idf/components/esp_hw_support/port/esp32/private_include -IC:/epressif/v4.4.4/esp-idf/components/heap/include -IC:/epressif/v4.4.4/esp-idf/components/log/include -IC:/epressif/v4.4.4/esp-idf/components/lwip/include/apps -IC:/epressif/v4.4.4/esp-idf/components/lwip/include/apps/sntp -IC:/epressif/v4.4.4/esp-idf/components/lwip/lwip/src/include -IC:/epressif/v4.4.4/esp-idf/components/lwip/port/esp32/include -IC:/epressif/v4.4.4/esp-idf/components/lwip/port/esp32/include/arch -IC:/epressif/v4.4.4/esp-idf/components/soc/include -IC:/epressif/v4.4.4/esp-idf/components/soc/esp32/. -IC:/epressif/v4.4.4/esp-idf/components/soc/esp32/include -IC:/epressif/v4.4.4/esp-idf/components/hal/esp32/include -IC:/epressif/v4.4.4/esp-idf/components/hal/include -IC:/epressif/v4.4.4/esp-idf/components/hal/platform_port/include -IC:/epressif/v4.4.4/esp-idf/components/esp_rom/include -IC:/epressif/v4.4.4/esp-idf/components/esp_rom/include/esp32 -IC:/epressif/v4.4.4/esp-idf/components/esp_rom/esp32 -IC:/epressif/v4.4.4/esp-idf/components/esp_common/include -IC:/epressif/v4.4.4/esp-idf/components/esp_system/include -IC:/epressif/v4.4.4/esp-idf/components/esp_system/port/soc -IC:/epressif/v4.4.4/esp-idf/components/esp_system/port/public_compat -IC:/epressif/v4.4.4/esp-idf/components/esp32/include -IC:/epressif/v4.4.4/esp-idf/components/xtensa/include -IC:/epressif/v4.4.4/esp-idf/components/xtensa/esp32/include -IC:/epressif/v4.4.4/esp-idf/components/driver/include -IC:/epressif/v4.4.4/esp-idf/components/driver/esp32/include -IC:/epressif/v4.4.4/esp-idf/components/esp_pm/include -IC:/epressif/v4.4.4/esp-idf/components/esp_ringbuf/include -IC:/epressif/v4.4.4/esp-idf/components/efuse/include -IC:/epressif/v4.4.4/esp-idf/components/efuse/esp32/include -IC:/epressif/v4.4.4/esp-idf/components/vfs/include -IC:/epressif/v4.4.4/esp-idf/components/esp_wifi/include -IC:/epressif/v4.4.4/esp-idf/components/esp_event/include -IC:/epressif/v4.4.4/esp-idf/components/esp_netif/include -IC:/epressif/v4.4.4/esp-idf/components/esp_eth/include -IC:/epressif/v4.4.4/esp-idf/components/tcpip_adapter/include -IC:/epressif/v4.4.4/esp-idf/components/esp_phy/include -IC:/epressif/v4.4.4/esp-idf/components/esp_phy/esp32/include -IC:/epressif/v4.4.4/esp-idf/components/esp_ipc/include -IC:/epressif/v4.4.4/esp-idf/components/app_trace/include -IC:/epressif/v4.4.4/esp-idf/components/esp_timer/include -IC:/epressif/v4.4.4/esp-idf/components/mbedtls/port/include -IC:/epressif/v4.4.4/esp-idf/components/mbedtls/mbedtls/include -IC:/epressif/v4.4.4/esp-idf/components/mbedtls/esp_crt_bundle/include -IC:/epressif/v4.4.4/esp-idf/components/app_update/include -IC:/epressif/v4.4.4/esp-idf/components/spi_flash/include -IC:/epressif/v4.4.4/esp-idf/components/bootloader_support/include -IC:/epressif/v4.4.4/esp-idf/components/nvs_flash/include -IC:/epressif/v4.4.4/esp-idf/components/pthread/include -IC:/epressif/v4.4.4/esp-idf/components/esp_gdbstub/include -IC:/epressif/v4.4.4/esp-idf/components/esp_gdbstub/xtensa -IC:/epressif/v4.4.4/esp-idf/components/esp_gdbstub/esp32 -IC:/epressif/v4.4.4/esp-idf/components/espcoredump/include -IC:/epressif/v4.4.4/esp-idf/components/espcoredump/include/port/xtensa -IC:/epressif/v4.4.4/esp-idf/components/wpa_supplicant/include -IC:/epressif/v4.4.4/esp-idf/components/wpa_supplicant/port/include -IC:/epressif/v4.4.4/esp-idf/components/wpa_supplicant/esp_supplicant/include -IC:/epressif/v4.4.4/esp-idf/components/ieee802154/include -IC:/epressif/v4.4.4/esp-idf/components/console -IC:/epressif/v4.4.4/esp-idf/components/asio/asio/asio/include -IC:/epressif/v4.4.4/esp-idf/components/asio/port/include -IC:/epressif/v4.4.4/esp-idf/components/cbor/port/include -IC:/epressif/v4.4.4/esp-idf/components/unity/include -IC:/epressif/v4.4.4/esp-idf/components/unity/unity/src -IC:/epressif/v4.4.4/esp-idf/components/cmock/CMock/src -IC:/epressif/v4.4.4/esp-idf/components/coap/port/include -IC:/epressif/v4.4.4/esp-idf/components/coap/libcoap/include -IC:/epressif/v4.4.4/esp-idf/components/nghttp/port/include -IC:/epressif/v4.4.4/esp-idf/components/nghttp/nghttp2/lib/includes -IC:/epressif/v4.4.4/esp-idf/components/esp-tls -IC:/epressif/v4.4.4/esp-idf/components/esp-tls/esp-tls-crypto -IC:/epressif/v4.4.4/esp-idf/components/esp32_composite_video_lib/include -IC:/epressif/v4.4.4/esp-idf/components/esp_adc_cal/include -IC:/epressif/v4.4.4/esp-idf/components/esp_hid/include -IC:/epressif/v4.4.4/esp-idf/components/tcp_transport/include -IC:/epressif/v4.4.4/esp-idf/components/esp_http_client/include -IC:/epressif/v4.4.4/esp-idf/components/esp_http_server/include -IC:/epressif/v4.4.4/esp-idf/components/esp_https_ota/include -IC:/epressif/v4.4.4/esp-idf/components/esp_lcd/include -IC:/epressif/v4.4.4/esp-idf/components/esp_lcd/interface -IC:/epressif/v4.4.4/esp-idf/components/protobuf-c/protobuf-c -IC:/epressif/v4.4.4/esp-idf/components/protocomm/include/common -IC:/epressif/v4.4.4/esp-idf/components/protocomm/include/security -IC:/epressif/v4.4.4/esp-idf/components/protocomm/include/transports -IC:/epressif/v4.4.4/esp-idf/components/mdns/include -IC:/epressif/v4.4.4/esp-idf/components/esp_local_ctrl/include -IC:/epressif/v4.4.4/esp-idf/components/sdmmc/include -IC:/epressif/v4.4.4/esp-idf/components/esp_serial_slave_link/include -IC:/epressif/v4.4.4/esp-idf/components/esp_websocket_client/include -IC:/epressif/v4.4.4/esp-idf/components/expat/expat/expat/lib -IC:/epressif/v4.4.4/esp-idf/components/expat/port/include -IC:/epressif/v4.4.4/esp-idf/components/wear_levelling/include -IC:/epressif/v4.4.4/esp-idf/components/fatfs/diskio -IC:/epressif/v4.4.4/esp-idf/components/fatfs/vfs -IC:/epressif/v4.4.4/esp-idf/components/fatfs/src -IC:/epressif/v4.4.4/esp-idf/components/freemodbus/freemodbus/common/include -IC:/epressif/v4.4.4/esp-idf/components/idf_test/include -IC:/epressif/v4.4.4/esp-idf/components/idf_test/include/esp32 -IC:/epressif/v4.4.4/esp-idf/components/jsmn/include -IC:/epressif/v4.4.4/esp-idf/components/json/cJSON -IC:/epressif/v4.4.4/esp-idf/components/libsodium/libsodium/src/libsodium/include -IC:/epressif/v4.4.4/esp-idf/components/libsodium/port_include -IC:/epressif/v4.4.4/esp-idf/components/lvgl -IC:/epressif/v4.4.4/esp-idf/components/lvgl/src -IC:/epressif/v4.4.4/esp-idf/components -IC:/epressif/v4.4.4/esp-idf/components/mqtt/esp-mqtt/include -IC:/epressif/v4.4.4/esp-idf/components/openssl/include -IC:/epressif/v4.4.4/esp-idf/components/perfmon/include -IC:/epressif/v4.4.4/esp-idf/components/spiffs/include -IC:/epressif/v4.4.4/esp-idf/components/ulp/include -IC:/epressif/v4.4.4/esp-idf/components/wifi_provisioning/include -mlongcalls -Wno-frame-address  -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -ggdb -Og -fmacro-prefix-map=C:/Video_comp_esp32=. -fmacro-prefix-map=C:/epressif/v4.4.4/esp-idf=IDF -fstrict-volatile-bitfields -Wno-error=unused-but-set-variable -fno-jump-tables -fno-tree-switch-conversion -std=gnu99 -Wno-old-style-declaration -D_GNU_SOURCE -DIDF_VER=\"v4.4.4\" -DESP_PLATFORM -D_POSIX_READER_WRITER_LOCKS -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -MF esp-idf\main\CMakeFiles\__idf_main.dir\main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/main.c.obj -c C:/Video_comp_esp32/main/main.c
C:/Video_comp_esp32/main/main.c: In function 'app_main':
C:/Video_comp_esp32/main/main.c:5:5: error: implicit declaration of function 'video_test_pal'; did you mean 'video_stop'? [-Werror=implicit-function-declaration]
     video_test_pal(VIDEO_TEST_PM5544);
     ^~~~~~~~~~~~~~
     video_stop
C:/Video_comp_esp32/main/main.c:5:20: error: 'VIDEO_TEST_PM5544' undeclared (first use in this function)
     video_test_pal(VIDEO_TEST_PM5544);
                    ^~~~~~~~~~~~~~~~~
C:/Video_comp_esp32/main/main.c:5:20: note: each undeclared identifier is reported only once for each function it appears in
cc1.exe: some warnings being treated as errors
[1217/1224] Building C object esp-idf/wifi_provisioning/CMakeFiles/__idf_wifi_provisioning.dir/src/manager.c.obj
ninja: build stopped: subcommand failed.

 *  The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command ninja " terminated with exit code: 1.

**Comment by danjulio** [comment]
I'm not sure what you are compiling but this does not look like my project.  My main.c does not call video_test_pal(VIDEO_TEST_PM5544).  And I wouldn't expect my project to be unpacked in a directory called "Video_comp_esp32".  Are you sure you're in the expected place as you build this?

**Comment by Igor-kopanitsa** [comment]
...sorry I have missed the right project (aquaticus/esp32_composite_video_lib)
